import fetch from 'node-fetch';

// Use production endpoint by default since you've configured the variables in Cloudflare.
// Can override via env var, e.g., TARGET_URL=http://localhost:8787 npm run test:pr
const TARGET_URL = process.env.TARGET_URL || 'https://bkraiskillsmcp.pages.dev';

async function main() {
    console.log(`===============================================`);
    console.log(`[System] Initializing GitHub PR Automation Test`);
    console.log(`[Gateway] Target Edge URL: ${TARGET_URL}`);
    console.log(`===============================================\n`);

    // -------------------------------------------------------------
    // Step 1: Verify the Cloudflare Environment Variables
    // -------------------------------------------------------------
    console.log(`[1/2] Testing Edge GitHub App Auth keys via /api/github/test-auth...`);
    try {
        const authRes = await fetch(`${TARGET_URL}/api/github/test-auth`);
        const authBody = await authRes.json().catch(() => null);
        
        if (!authRes.ok) {
            console.error(`❌ [Auth Error] ${authRes.status} ${authRes.statusText}`);
            if (authBody) console.error(`Response details:`, JSON.stringify(authBody, null, 2));
            
            console.log(`\n[Diagnose] The secure keys are either missing or incorrect.`);
            console.log(`Please ensure the following are exactly set in your Cloudflare Pages Settings -> Environment Variables:`);
            console.log(`  - GITHUB_APP_ID`);
            console.log(`  - GITHUB_INSTALLATION_ID`);
            console.log(`  - GITHUB_PRIVATE_KEY`);
            return;
        }

        console.log(`✅ Auth signature valid! Temporary edge token successfully minted.\n`);
    } catch (e: any) {
        console.error(`❌ [Connection Error] Failed to reach ${TARGET_URL}:`, e.message);
        return;
    }

    // -------------------------------------------------------------
    // Step 2: Fire the REST Fallback payload imitating the MCP 
    // -------------------------------------------------------------
    console.log(`[2/2] Transmitting PR Blueprint to /api/test-pr...`);
    
    // NOTE: For this to work, ensure your Cloudflare App has permissions 
    // to write to 'mwildanhalhasan/your-repo-name' or whichever is targeted.
    
    // Please update targetOwner and targetRepo with the repository you want to test against:
    const targetOwner = process.env.GITHUB_OWNER || 'your-github-username';
    const targetRepo = process.env.GITHUB_REPO || 'your-repo-name';

    const branchSuffix = Math.floor(Date.now() / 1000);
    const prPayload = {
        owner: targetOwner,
        repo: targetRepo,
        baseBranch: 'main',
        newBranch: `edge-pr-test-${branchSuffix}`,
        title: 'test: Edge Workflow PR Verification',
        body: 'This PR was automatically generated by the Edge REST Fallback endpoint to verify the Cloudflare Environment authentication handshake.',
        files: [
            {
                path: 'docs/EDGE_PR_TEST.md',
                content: `# Automated Edge Authentication Test\n\nExecution Timestamp: ${new Date().toISOString()}\n\nStatus: Successfully hit Cloudflare Pages Worker and executed full Git PR via GitHub Apps.`
            }
        ]
    };

    console.log(`[System] Sending payload for branch: ${prPayload.newBranch}`);

    try {
        const prRes = await fetch(`${TARGET_URL}/api/test-pr`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(prPayload)
        });
        
        const prBody = await prRes.json().catch(() => null);

        if (!prRes.ok) {
            console.error(`❌ [PR Error] ${prRes.status} ${prRes.statusText}`);
            if (prBody) console.error(`Response details:`, JSON.stringify(prBody, null, 2));
            
            if (prRes.status === 404 || prRes.status === 403) {
                console.log(`\n[Diagnose] The GitHub App likely lacks permissions for ${targetOwner}/${targetRepo}.`);
                console.log(`Make sure you set GITHUB_OWNER=... and GITHUB_REPO=... before running or update the script variables.`);
            }
            return;
        }

        console.log(`✅ PR Executed Successfully!`);
        console.log(`[Output]`, JSON.stringify(prBody, null, 2));
        if (prBody?.data?.html_url) {
            console.log(`\n🎉 -> View your new Pull Request here: ${prBody.data.html_url}`);
        }
    } catch(e: any) {
        console.error(`❌ [Connection Error] Failed to execute PR test:`, e.message);
    }
}

main();
